version: "3"

services:
  postgres:
    container_name: ${APP_NAME}_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: ${APP_NAME}_go
    build:
      context: .
    depends_on:
      - postgres

volumes:
# create the volume for persisting data.
  dbdata: 